# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 20f00fc4812fed4e47e19a6dc4560a4d7c128e85fdb62f4c4b037c25a85ad502d9cb6269f46098f0f4928f266e3c11cdbf167386ebb7e325a98a1e3c144f7715

test:
  secret_key_base: 5ccc9f209a03fca5e82e21070497fd09abf5d84243dba07e9a5a66130ff4c2891e361b24602672ed921ba3f12c1448438ec79c1a0ff92d9cf1f5ea4c72204f2e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
